[project]
name = "ige-chess"
version = "0.1.0"
description = "Play me in chess!"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chess>=1.11.2",
    "fastapi>=0.117.1",
    "jinja2>=3.1.6",
    "uvicorn>=0.37.0",
]
