[project]
name = "ige-chess"
version = "0.1.0"
description = "Play me in chess!"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.117.1",
    "jinja2>=3.1.6",
    "numpy>=2.3.3",
    "python-chess>=1.999",
    "tensorflow>=2.20.0",
    "uvicorn>=0.37.0",
]
